package de.flozo.cv;

public class Main {

    // constants
    public static final String APPLICATION_NAME = "CVgen";
    public static final String VERSION_NUMBER = "0.1";
    public static final String VERSION_DATE = "2022-07-05";

    public static final String REPO_URL = String.format("https://github.com/flozo/%1$s",
            APPLICATION_NAME);
    public static final String VERSION_INFO_LATEX_HEADER = String.format("%% =====  LaTeX code generated by %1$s v%2$s (%3$s)\n%% =====  %1$s by flozo (%4$s)",
            APPLICATION_NAME, VERSION_NUMBER, VERSION_DATE, REPO_URL);
    public static final String VERSION_INFO_PDF_META_DATA = String.format("%1$s v%2$s (%3$s); visit %4$s",
            APPLICATION_NAME, VERSION_NUMBER, VERSION_DATE, REPO_URL);


    public static void main(String[] args) {


//        ConfigDirectory configDirectory = ConfigDirectory.fromDefaultDirectory(APPLICATION_NAME);
//        configDirectory.createIfNotExists();
//        System.out.println(configDirectory);
//        MasterConfigFile masterConfigFile = MasterConfigFile.withDefaultFileName(configDirectory);
//        System.out.println(masterConfigFile);
//        ConfigGroup.MASTER.writeToFile(configDirectory, VERSION_INFO_PDF_META_DATA);
////        masterConfigFile.writeProperties();
//        masterConfigFile.readProperties();
//
//        ConfigGroup.LETTER_GENERAL.writeToFile(configDirectory,VERSION_INFO_PDF_META_DATA);
//        ConfigGroup.LETTER_GEOMETRY.writeToFile(configDirectory,VERSION_INFO_PDF_META_DATA);
//        ConfigGroup.LETTER_COLORS.writeToFile(configDirectory,VERSION_INFO_PDF_META_DATA);
//        ConfigGroup.LETTER_FONTS.writeToFile(configDirectory,VERSION_INFO_PDF_META_DATA);




    }
}
